name: Generate Activity Graph

on:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 2 AM
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Activity Graph
        uses: ashutosh00710/github-readme-activity-graph@master
        with:
          USERNAME: 567Prince
          THEME: react-dark
          COLOR: 00BFFF
          LINE_COLOR: 00BFFF
          POINT_COLOR: FFFFFF
          AREA: true
          HIDE_BORDER: true
