name: Update Visitors Counter

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-visitors:
    runs-on: ubuntu-latest
    steps:
      - name: Update Visitors Badge
        uses: sarowar/visitors-badge@v1
        with:
          repo: 567Prince
          token: ${{ secrets.GITHUB_TOKEN }}
